name: nuget
on:
  push:
    branches:
      - main # Default release branch
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Update nuget version
        run: dotnet run D:/Repository/BoysheO.UnityLibrary/BoysheO.UnityLibrary.Dotnet/UpdateProjectsPackageVersion

      - name: Build all projects
        run: dotnet build -c Release BoysheO.UnityLibrary.Dotnet/BoysheO.UnityLibrary.sln

      - name: Publish to Nuget 
        run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n 
