name: nuget
on:
  push:
    tags:
      - '*'
      
jobs:
  publish:
    name: build, pack & publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Update nuget version
        run: dotnet run
        working-directory: BoysheO.UnityLibrary.Dotnet/UpdateProjectsPackageVersion

      - name: Get project path
        id: get_project_path
        run: dotnet run -- BoysheO.Collection.Abstractions_0.0.1>> $GITHUB_ENV
        working-directory: BoysheO.UnityLibrary.Dotnet/ResolveTag

      - name: Build project
        run: dotnet build ${{ env.PROJECT_DIR }}/*.csproj --configuration Release

      - name: Build all projects
        run: dotnet build -c Release BoysheO.UnityLibrary.Dotnet/BoysheO.UnityLibrary.sln

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
